name: Deploy FNA Sample

on:
  push:
    branches:
      - fna-net8
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        variant: [Release]
    runs-on: ${{ matrix.os }}
    name: Build FNA Sample
    steps:
      - name: Check out source
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Install dotnet workloads
        run: |
          dotnet workload install wasm-tools
          dotnet workload install wasm-experimental
      - name: Publish project
        run: dotnet publish
      - name: Test path
        run: |
          cd /home/runner/work/SdlWasmSample/SdlWasmSample/SdlWasmSample/bin/Release/net8.0/publish
          cd wwwroot
          ls
      - name: Save published files for download
        uses: actions/upload-artifact@v4
        with:
          name: Published Files
          path: |
            /home/runner/work/SdlWasmSample/SdlWasmSample/SdlWasmSample/bin/Release/net8.0/publish/wwwroot/*
          if-no-files-found: error
      - name: Fix permissions
        run: |
          chmod -c -R +rX "/home/runner/work/SdlWasmSample/SdlWasmSample/SdlWasmSample/bin/Release/net8.0/publish/wwwroot/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Save published files for GH Pages
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: /home/runner/work/SdlWasmSample/SdlWasmSample/SdlWasmSample/bin/Release/net8.0/publish/wwwroot/
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest]
        variant: [Release]
    runs-on: ${{ matrix.os }}
    needs: build
    #required for Github Pages deploy
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Deploy FNA Sample
    steps:
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4
          
      
      