name: Deploy FNA Sample

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        variant: [Release]
    runs-on: ${{ matrix.os }}
    name: Build FNA Sample
    steps:
      - name: Check out source
        uses: actions/checkout@v4
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Install dotnet workloads
        run: |
          dotnet workload install wasm-tools
          dotnet workload install wasm-experimental
      - name: Publish project
        run: dotnet publish
      - name: Test path
        run: |
          cd /home/runner/work/SdlWasmSample/SdlWasmSample/SdlWasmSample/bin/Release/net8.0/publish
          cd wwwroot
          ls
      - name: Save published files for download
        uses: actions/upload-artifact@v4
        with:
          name: Published Files
          path: |
            /home/runner/work/SdlWasmSample/SdlWasmSample/SdlWasmSample/bin/Release/net8.0/publish/wwwroot/*
          if-no-files-found: error
      - name: Package published files for GH Pages
        run: |
          cd /home/runner/work/SdlWasmSample/SdlWasmSample/SdlWasmSample/bin/Release/net8.0/publish
          tar -czvf publish.tar.gz wwwroot/*
      - name: Save published files for GH Pages
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: |
            /home/runner/work/SdlWasmSample/SdlWasmSample/SdlWasmSample/bin/Release/net8.0/publish/publish.tar.gz          
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest]
        variant: [Release]
    runs-on: ${{ matrix.os }}
    needs: build
    #required for Github Pages deploy
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Deploy FNA Sample
    steps:
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4
          
      
      